// Code generated by goctl. DO NOT EDIT.
// Source: register.proto

package register_client

import (
	"context"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
	"grpc-common/types/register"
)

type (
	CaptchaReq = register.types
	RegReq     = register.types
	RegRes     = register.types

	Register interface {
		Register(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error)
	}

	defaultRegister struct {
		cli zrpc.Client
	}
)

func NewRegister(cli zrpc.Client) Register {
	return &defaultRegister{
		cli: cli,
	}
}

func (m *defaultRegister) Register(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error) {
	client := register.types.NewRegisterClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}
