// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/zeromicro/go-zero/rest"
	"net/http"
)

type Routes struct {
	server *rest.Server
	Middlewares []rest.Middleware
}

func NewRouters(server *rest.Server) *Routes  {
	return &Routes{server: server}
}

func (r *Routes) Get(path string, handlerFunc http.HandlerFunc)  {
	r.server.AddRoutes(
		rest.WithMiddlewares(
		r.Middlewares,
		rest.Route{
				Method:  http.MethodGet,
				Path:    path,
				Handler: handlerFunc,
		    },
		),
	)
}

func (r *Routes) Post(path string, handlerFunc http.HandlerFunc)  {
	r.server.AddRoutes(
		rest.WithMiddlewares(
			r.Middlewares,
			rest.Route{
				Method:  http.MethodPost,
				Path:    path,
				Handler: handlerFunc,
			},
		),
	)
}

func (r *Routes) Group() *Routes  {
	return &Routes{
		server:      r.server,
	}
}

